### ISSUE TITLE
Malody Store API的使用问题

### ISSUE THREAD

**Issue by Xenolies** [Pocket-Tech/QiuSheng#1]
大佬您好，我最近准备使用Go语言开发一个获取Malody谱面信息，然后下载的功能，现在我找到了Malody Store API的文档，但是能力有限没看明白＞︿＜。
遇到了几个问题:
1.uid，api，key这三个参数如何设置？
2.请求的网址是那个？
3.心知天气APi是这样的格式 https://api.seniverse.com/v3/weather/now.json?key=你的私钥
&location=查询城市的拼音&language=zh-Hans&unit=c ，Malody 的API是啥格式的呢？

网上找了很多，才找到这一个Malody Store API项目≡(▔﹏▔)≡，麻烦大佬了

**Comment by windors** [comment]
你的谱面服务器/api/store/info?api=`202112`&uid=`xxxxxx`&key=`xxxxxxxx`&t=`xxxxxxx`
根据Store API里写的路径和参数来，参数也是 &sid=xxx 的格式，Store API规定了参数、路径、返回值格式等信息，当用户在《Malody V》里设定了谱面服务器后，《Malody V》会根据Store API中规定的指定参数、路径去访问指定的URL。

**Comment by Xenolies** [comment]
原来是这样使用吗？，感谢^ω^

**Comment by Xenolies** [comment]
请问API请求的网址是这个吗https://m.mugzone.net/

**Comment by Xenolies** [comment]
我搞错了，这个好像是要在自己搭建谱面服务器来搞，我还以为获取的是用这个来获取malody官方谱面服务器一些歌曲信息啥的

**Comment by KADGang** [comment]
这个api文档是规定你的私服来实现客户端所请求功能的标准。我感觉malody v那边应该是出于某种原因不再使用官方谱面服务器了，所以才制定了这么一个api标准让私服搭建者自己来实现的。

**Comment by KADGang** [comment]
如果想要获取官方谱面服务器的信息，在他们官方还没有开放公共api的情况下，应该还是需要通过编写爬虫的形式来实现对应的功能。
